### ISSUE TITLE
GUI's in C++ and header

### ISSUE THREAD

**Issue by ghost** [CodePadApp/codepad-issues#73]
Cant use SFML to create GUI's. Can't create files as .h, nor .hpp (headers).  Need SFML and .h/.hpp headers files to create GUI or any games.

**Comment by ethan-vanderheijden** [comment]
Sorry for the delay, but CodePad now supports SFML and .h/.hpp files. We also support Makefiles for more complicated C++ projects.

You can check out a SFML demo here:
https://codepad.app/edit/5563xcqb
