### ISSUE TITLE
CodePad 

### ISSUE THREAD

**Issue by jspangle090** [CodePadApp/codepad-issues#74]
CodePad App is showing not connected to server.  Not sure how as I am hardwired on my desktop.  Any ideas how to fix this?

**Comment by ethan-vanderheijden** [comment]
Sorry, our server has been going down intermittently today. We are working on a fix, and things should be better within a day or two. I'll keep you updated on the status.

**Comment by jspangle090** [comment]
Thank you for that information.

**Comment by ethan-vanderheijden** [comment]
The issue should be resolved. Please, don’t hesitate to reach out if you encounter any difficulties.

**Comment by jspangle090** [comment]
Thank you for the update.
